// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth.sql

package db

import (
	"context"
)

const checkUserCredentials = `-- name: CheckUserCredentials :one
SELECT u.password_hash
FROM users u
WHERE u.user_name = $1
`

func (q *Queries) CheckUserCredentials(ctx context.Context, userName string) (string, error) {
	row := q.db.QueryRow(ctx, checkUserCredentials, userName)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}
