// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Country struct {
	ID          pgtype.UUID
	CountryName string
}

type Genre struct {
	ID        pgtype.UUID
	Genre     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Movie struct {
	ID          pgtype.UUID
	Title       string
	Score       pgtype.Numeric
	Picture     string
	ReleaseDate pgtype.Date
	Synopsis    string
	PublisherID pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type MovieGenre struct {
	MovieID pgtype.UUID
	GenreID pgtype.UUID
}

type Publisher struct {
	ID            pgtype.UUID
	PublisherName string
	YearFounded   int32
	CountryID     pgtype.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	UserName     string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
